### ISSUE TITLE
Доп задания

### ISSUE THREAD

**Issue by bodrovis** [Back2Basics1337/blinkapp#1]
1. Стилизовать элемент для выбора файла на этой странице https://blinkproject.herokuapp.com/ideas/new как-нибудь нестандартно (типа кнопка зелёная и с чёрной границией, поле закрашено серым - например)
2. Сделать сайт респонсивным (чтобы элементы помещались в маленькие экраны) - Bootstrap это позволяет сделать
3. Интегрировать любой плагин jQuery UI
4. Это даже можно отнести к вопросам - почему такая страшная страница новостей? У новости обычно есть дата публикации, ссылка читать далее и т.п.  И это не поэма Пушкина, текст по центру равнять не надо

**Comment by bodrovis** [comment]
P.S. Впрочем, кнопку Отправить в форме надо тоже стилизовать - это вообще делается за 5 секунд с помощью Bootstrap

**Comment by Back2Basics1337** [comment]
Не понимаю почему моя стилизация не применяется на heroku, хотя локально я изменил и кнопки и стиха у меня локально нет.

**Comment by bodrovis** [comment]
Проверь кэши, посмотри какие вообще стили применяются, почитай инет и поищи подобные случаи
